interface Data {
  id: number;
  title: string;
  image: string;
  desc: string;
  category: string;
}

interface Skill {
  id: number;
  label: string;
  value: number;
}
interface Package {
  id: number;
  title: string;
  label: string;
  category: string;
  capacity: string;
  support: string;
  price: number;
  color: string;
}

export const Data: Data[] = [
  {
    id: 101,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art41.png",
    desc: "African Queens Of Gold",
    category: "design",
  },
  {
    id: 102,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art46.png",
    desc: "African Queens Of Gold",
    category: "photos",
  },
  {
    id: 103,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art49.png",
    desc: "African Queens Of Gold",
    category: "art",
  },
  {
    id: 104,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art51.png",
    desc: "African Queens Of Gold",
    category: "design",
  },
  {
    id: 105,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art56.png",
    desc: "African Queens Of Gold",
    category: "photos",
  },
  {
    id: 106,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art54.png",
    desc: "African Queens Of Gold",
    category: "art",
  },
  {
    id: 107,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art8.png",
    desc: "African Queens Of Gold",
    category: "design",
  },
  {
    id: 108,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art12.png",
    desc: "African Queens Of Gold",
    category: "photos",
  },
  {
    id: 109,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/queen.png",
    desc: "African Queens Of Gold",
    category: "art",
  },
  {
    id: 110,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art11.png",
    desc: "Color Clears Drawing Art",
    category: "design",
  },
  {
    id: 111,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/blind.png",
    desc: "Color Clears Drawing Art",
    category: "photos",
  },
  {
    id: 112,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art27.png",
    desc: "Drawing Drawing Art",
    category: "art",
  },
  {
    id: 113,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art42.png",
    desc: "Japanese Landscapes",
    category: "design",
  },
  {
    id: 114,
    title: "Moon Vs Sun Fox Creations",
    image: "/images/art43.png",
    desc: "Fox Creation Art",
    category: "photos",
  },
  {
    id: 115,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art45.png",
    desc: "Japanese Landscapes",
    category: "art",
  },
  {
    id: 116,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art50.png",
    desc: "Color Clears",
    category: "design",
  },
  {
    id: 117,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art53.png",
    desc: "Color Clears",
    category: "photos",
  },
  {
    id: 118,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art57.png",
    desc: "Color Clears",
    category: "art",
  },
  {
    id: 119,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art52.png",
    desc: "Color Clears Lion Pair Creation",
    category: "design",
  },
  {
    id: 120,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art55.png",
    desc: "Color Clears Lion Pair Creation",
    category: "photos",
  },
  {
    id: 121,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art44.png",
    desc: "Color Clears",
    category: "art",
  },
  {
    id: 122,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art10.png",
    desc: "Color Clears",
    category: "design",
  },
  {
    id: 123,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art29.png",
    desc: "Drawing Art Work",
    category: "photos",
  },
  {
    id: 124,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art22.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 125,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art30.png",
    desc: "Drawing Art Work",
    category: "design",
  },
  {
    id: 126,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art31.png",
    desc: "Drawing Art Work",
    category: "photos",
  },
  {
    id: 127,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art20.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 128,
    title: "Moon Vs Sun Fox Creations",
    image: "/images/art9.png",
    desc: "Fox Creation",
    category: "design",
  },
  {
    id: 129,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art21.png",
    desc: "Drawing Art Work",
    category: "photos",
  },
  {
    id: 130,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art28.png",
    desc: "Drawing Art Work",
    category: "photos",
  },
  {
    id: 131,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art32.png",
    desc: "Art Work",
    category: "art",
  },
  {
    id: 132,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art33.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 133,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art34.png",
    desc: "Sketch Art",
    category: "art",
  },
  {
    id: 134,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art35.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 135,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art36.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 136,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art37.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 137,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art38.png",
    desc: "Sketch Art",
    category: "art",
  },
  {
    id: 138,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art39.png",
    desc: "Sketch Art",
    category: "art",
  },
  {
    id: 139,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art40.png",
    desc: "Sketch Art",
    category: "art",
  },
  {
    id: 140,
    title: "Nature Photos",
    image: "/images/ph1.png",
    desc: "Nature Explore",
    category: "art",
  },
  {
    id: 141,
    title: "Nature Photos",
    image: "/images/ph2.png",
    desc: "Nature Explore",
    category: "art",
  },
  {
    id: 142,
    title: "Nature Photos",
    image: "/images/ph3.png",
    desc: "Nature Explore",
    category: "art",
  },
  {
    id: 143,
    title: "Nature Photos",
    image: "/images/ph4.png",
    desc: "Nature Explore",
    category: "art",
  },
  {
    id: 144,
    title: "Nature Photos",
    image: "/images/ph5.png",
    desc: "Nature Explore",
    category: "art",
  },
  {
    id: 145,
    title: "Nature Photos",
    image: "/images/ph6.png",
    desc: "Nature Explore",
    category: "art",
  },
  {
    id: 146,
    title: "Nature Photos",
    image: "/images/ph10.png",
    desc: "Nature Explore",
    category: "art",
  },
  {
    id: 147,
    title: "Nature Photos",
    image: "/images/ph8.png",
    desc: "Nature Explore",
    category: "art",
  },
  {
    id: 148,
    title: "Nature Photos",
    image: "/images/ph9.png",
    desc: "Nature Explore",
    category: "art",
  },
  {
    id: 149,
    title: "Nature Photos",
    image: "/images/ph7.png",
    desc: "Nature Explore",
    category: "art",
  },
  //art ai
  {
    id: 150,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art23.png",
    desc: "Art Work",
    category: "art",
  },
  {
    id: 151,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art24.png",
    desc: "Art Work",
    category: "art",
  },
  {
    id: 152,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art25.png",
    desc: "Art Work",
    category: "art",
  },
  {
    id: 153,
    title: "Moon Vs Sun Fox Creations",
    image: "/images/art3.png",
    desc: "Fox Creation",
    category: "art",
  },
  {
    id: 154,
    title: "Moon Vs Sun Fox Creations",
    image: "/images/art6.png",
    desc: "Fox Creation",
    category: "art",
  },
  {
    id: 155,
    title: "Moon Vs Sun Fox Creations",
    image: "/images/foxart.png",
    desc: "Fox Creation",
    category: "art",
  },
  {
    id: 156,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art14.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 157,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art18.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 158,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art17.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 159,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art16.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 160,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art7.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 161,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art13.png",
    desc: "Drawing Art Work",
    category: "art",
  },
  {
    id: 162,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art5.png",
    desc: "Japanese Landscapes",
    category: "art",
  },
  {
    id: 163,
    title: "The Gold Goddess Sun vs Moon",
    image: "/images/art15.png",
    desc: "Sketch Art",
    category: "art",
  },
];

export const Skills: Skill[] = [
  {
    id: 1,
    label: "Photography",
    value: 95,
  },
  {
    id: 2,
    label: "Painting",
    value: 89,
  },
  {
    id: 3,
    label: "AI Creations",
    value: 87,
  },
];
export const PackagesData: Package[] = [
  {
    id: 1,
    title: "Basic",
    label: "Web Design",
    category: "Photography",
    capacity: "1GB Storage",
    support: "Mail Support",
    price: 10,
    color: "#616161",
  },
  {
    id: 2,
    title: "Pro",
    label: "Web Design",
    category: "Photography",
    capacity: "50GB Storage",
    support: "Endless Support",
    price: 25,
    color: "#009688",
  },
  {
    id: 3,
    title: "Premium",
    label: "Web Design",
    category: "Photography",
    capacity: "Unlimited Storage",
    support: "Endless Support",
    price: 50,
    color: "#616161",
  },
];

export const Tags: string[] = [
  "visual",
  "creative",
  "drawing",
  "fineart",
  "portrait",
  "nature",
  "photo",
  "illustration",
  "photoshop",
  "visualartistic",
  "arte",
  "sketch",
];
